### ISSUE TITLE
Objective C implementation

### ISSUE THREAD

**Issue by chrisjdavis** [cacmartinez/CCMRadarView#1]
I see that your other IBDesigner class has both a Swift and ObjC implementation. I was wondering/hoping if you were going to also convert this to ObjC? I could really use it in an app right about now.

Thanks.

**Comment by cacmartinez** [comment]
I might do an ObjC implementation later, although if you are using XCode 6 and iOS SDK 8.1 in theory you could also use this class with objective-c code using the Xcode-generated header file. The name of this header is your product module name followed by adding "-Swift.h" (`#import "{nameOfYourModule}-Swift.h"`). This should let you use any swift class with the public or internal modifiers in your project from the objC classes where you import this header.

**Comment by chrisjdavis** [comment]
Yeah that was my first step, but I couldn't get it to work. Updating xCode to the newest beta and trying again.

**Comment by dis123** [comment]
I tried to implement swift code with my objective C code as per apple documentation how to integrate swift file in objective C code. Swift code is also trigger but not able to see the animation. I debug the code and found that in "override func animationDidStop(anim: CAAnimation!, finished flag: Bool)" the value of flag is always comes 'false' so that animation is not working with objective C code. Can you please look into this why I am not able to see the animation in objective C Code.
